<?php
/**
 * Update all 12 Tour Types with rich SEO-optimized descriptions,
 * meta data, and translations (FR/DE/ES).
 *
 * Usage: php update_tour_types.php
 */

require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\TourType;

$tourTypes = [

    // ──────────────────────────────────────────────
    // 1. Wildlife Safari
    // ──────────────────────────────────────────────
    'wildlife-safari' => [
        'description' => "Experience the raw beauty of East Africa on a classic wildlife safari through Tanzania's most iconic national parks and game reserves. From the vast Serengeti plains — home to the Big Five — to the wildlife-packed Ngorongoro Crater, every game drive reveals extraordinary encounters with lions, elephants, leopards, and hundreds of bird species.\n\nOur expert Tanzanian guides know every waterhole, migration corridor, and hidden kopje. Whether you choose an open-roof 4×4 game drive at dawn, a walking safari in Ruaha, or a night drive in Tarangire, each outing is tailored to your interests and pace.\n\nWildlife safaris in Tanzania suit first-time visitors and seasoned travellers alike. We offer flexible durations — from three-day Ngorongoro highlights to ten-day cross-country expeditions — and pair every itinerary with hand-picked lodges, tented camps, or mobile fly-camps for maximum immersion in the African bush.",

        'meta_title'       => 'Wildlife Safari Tanzania | Big Five Game Drives | Lomo Safari',
        'meta_description' => 'Book a wildlife safari in Tanzania. Expert-guided Big Five game drives in the Serengeti, Ngorongoro Crater, Tarangire & Ruaha. Custom itineraries from 3–10 days.',
        'meta_keywords'    => 'wildlife safari tanzania, big five safari, serengeti game drive, ngorongoro safari, tanzania safari packages, african wildlife tour',

        'description_translations' => [
            'fr' => "Vivez la beauté brute de l'Afrique de l'Est lors d'un safari classique à travers les parcs nationaux et réserves les plus emblématiques de Tanzanie. Des vastes plaines du Serengeti — abritant les Big Five — au cratère du Ngorongoro regorgeant de faune, chaque safari révèle des rencontres extraordinaires avec lions, éléphants, léopards et des centaines d'espèces d'oiseaux.\n\nNos guides tanzaniens experts connaissent chaque point d'eau, chaque corridor de migration et chaque kopje caché. Que vous choisissiez un safari en 4×4 à toit ouvert à l'aube, une marche en brousse à Ruaha ou un safari nocturne à Tarangire, chaque sortie est adaptée à vos centres d'intérêt.\n\nNos safaris conviennent aux primo-visiteurs comme aux voyageurs aguerris. Nous proposons des durées flexibles — de trois jours dans le Ngorongoro à dix jours d'expédition — associés à des lodges, camps sous tente ou camps mobiles soigneusement sélectionnés.",
            'de' => "Erleben Sie die unberührte Schönheit Ostafrikas auf einer klassischen Wildlife-Safari durch Tansanias berühmteste Nationalparks und Wildreservate. Von den endlosen Serengeti-Ebenen — Heimat der Big Five — bis zum wildreichen Ngorongoro-Krater offenbart jede Pirschfahrt außergewöhnliche Begegnungen mit Löwen, Elefanten, Leoparden und Hunderten von Vogelarten.\n\nUnsere erfahrenen tansanischen Guides kennen jedes Wasserloch, jeden Migrationskorridor und jeden verborgenen Kopje. Ob Sie eine Safari im offenen 4×4 bei Sonnenaufgang, eine Buschwanderung in Ruaha oder eine Nachtfahrt in Tarangire wählen — jeder Ausflug wird auf Ihre Interessen abgestimmt.\n\nUnsere Safaris eignen sich für Erstbesucher und erfahrene Reisende gleichermaßen. Wir bieten flexible Reisedauern — von drei Tagen im Ngorongoro bis zu zehntägigen Expeditionen — mit handverlesenen Lodges, Zeltcamps oder mobilen Fly-Camps.",
            'es' => "Experimenta la belleza salvaje de África Oriental en un safari clásico por los parques nacionales y reservas más icónicos de Tanzania. Desde las vastas llanuras del Serengeti — hogar de los Cinco Grandes — hasta el cráter del Ngorongoro repleto de fauna, cada safari revela encuentros extraordinarios con leones, elefantes, leopardos y cientos de especies de aves.\n\nNuestros guías tanzanos expertos conocen cada abrevadero, corredor de migración y kopje escondido. Ya elijas un safari en 4×4 al amanecer, una caminata en Ruaha o un safari nocturno en Tarangire, cada salida se adapta a tus intereses.\n\nNuestros safaris se adaptan tanto a primerizos como a viajeros experimentados. Ofrecemos duraciones flexibles — desde tres días en el Ngorongoro hasta expediciones de diez días — con lodges, campamentos y fly-camps cuidadosamente seleccionados.",
        ],
    ],

    // ──────────────────────────────────────────────
    // 2. Great Migration
    // ──────────────────────────────────────────────
    'great-migration' => [
        'description' => "Witness the greatest wildlife spectacle on Earth — the Great Migration. Every year, over two million wildebeest, zebra, and gazelle trek across the Serengeti-Mara ecosystem in an endless cycle of birth, survival, and dramatic river crossings. Our migration safaris position you exactly where the action unfolds, season by season.\n\nFrom the calving season on the southern Serengeti plains (January–March), through the western corridor crossings of the Grumeti River (May–July), to the legendary Mara River crossings in the north (August–October), we track the herds with real-time intelligence from our ground teams.\n\nEvery migration safari includes expert naturalist guides, strategically located camps and lodges, and optional balloon flights over the herds at sunrise. Whether you have four days or two weeks, we design your itinerary around the migration's current position for front-row encounters with nature's most dramatic journey.",

        'meta_title'       => 'Great Migration Safari Tanzania | Wildebeest Crossing | Lomo Safari',
        'meta_description' => 'Follow the Great Migration across the Serengeti. Witness wildebeest river crossings, calving season & predator action. Expert-guided migration safaris year-round.',
        'meta_keywords'    => 'great migration safari, wildebeest migration, serengeti migration, mara river crossing, tanzania migration safari, calving season serengeti',

        'description_translations' => [
            'fr' => "Assistez au plus grand spectacle animalier de la planète — la Grande Migration. Chaque année, plus de deux millions de gnous, zèbres et gazelles traversent l'écosystème Serengeti-Mara dans un cycle sans fin de naissances, de survie et de traversées de rivières spectaculaires.\n\nDe la saison de mise bas dans les plaines sud du Serengeti (janvier–mars), aux traversées du corridor ouest sur la rivière Grumeti (mai–juillet), jusqu'aux légendaires traversées de la rivière Mara au nord (août–octobre), nous suivons les troupeaux grâce à nos équipes sur le terrain.\n\nChaque safari migration comprend des guides naturalistes experts, des camps stratégiquement situés et des vols en montgolfière optionnels au-dessus des troupeaux au lever du soleil.",
            'de' => "Erleben Sie das größte Wildtierspektakel der Erde — die Große Migration. Jedes Jahr ziehen über zwei Millionen Gnus, Zebras und Gazellen durch das Serengeti-Mara-Ökosystem in einem endlosen Kreislauf aus Geburt, Überleben und dramatischen Flussüberquerungen.\n\nVon der Kalbungszeit in den südlichen Serengeti-Ebenen (Januar–März), über die Grumeti-Flussüberquerungen im westlichen Korridor (Mai–Juli), bis zu den legendären Mara-Flussüberquerungen im Norden (August–Oktober) verfolgen wir die Herden mit Echtzeit-Informationen.\n\nJede Migrations-Safari umfasst erfahrene Naturführer, strategisch platzierte Camps und optionale Ballonfahrten über die Herden bei Sonnenaufgang.",
            'es' => "Presencia el mayor espectáculo de vida salvaje del planeta — la Gran Migración. Cada año, más de dos millones de ñus, cebras y gacelas recorren el ecosistema Serengeti-Mara en un ciclo interminable de nacimientos, supervivencia y dramáticos cruces de ríos.\n\nDesde la temporada de partos en las llanuras del sur del Serengeti (enero–marzo), pasando por los cruces del río Grumeti en el corredor occidental (mayo–julio), hasta los legendarios cruces del río Mara en el norte (agosto–octubre), seguimos a las manadas con información en tiempo real.\n\nCada safari de migración incluye guías naturalistas expertos, campamentos estratégicamente ubicados y vuelos opcionales en globo sobre las manadas al amanecer.",
        ],
    ],

    // ──────────────────────────────────────────────
    // 3. Luxury Safari
    // ──────────────────────────────────────────────
    'luxury-safari' => [
        'description' => "Indulge in the finest safari experience Africa has to offer. Our luxury safaris pair world-class wildlife viewing with five-star lodges, private game concessions, and bespoke itineraries designed for the most discerning travellers. Think sundowners on the crater rim, candlelit bush dinners under the stars, and exclusive access to areas where few vehicles venture.\n\nStay in award-winning properties — from the iconic Ngorongoro Crater Lodge and Four Seasons Safari Lodge Serengeti to intimate boutique tented camps in private conservancies. Every detail is curated: premium wines, personal butlers, private guides, and seamless charter flights between destinations.\n\nWhether it is a milestone celebration, a once-in-a-lifetime journey, or simply the way you prefer to travel, our luxury safaris transform a game drive into an unforgettable five-star experience. Combine bush and beach with a seamless Serengeti-to-Zanzibar transfer for the ultimate East African escape.",

        'meta_title'       => 'Luxury Safari Tanzania | 5-Star Lodges & Private Guides | Lomo Safari',
        'meta_description' => 'Experience luxury safaris in Tanzania. Five-star lodges, private concessions, personal butlers & bespoke itineraries in the Serengeti, Ngorongoro & Zanzibar.',
        'meta_keywords'    => 'luxury safari tanzania, five star safari, private safari lodge, ngorongoro crater lodge, serengeti luxury camp, bespoke safari africa',

        'description_translations' => [
            'fr' => "Offrez-vous la plus belle expérience safari que l'Afrique puisse proposer. Nos safaris de luxe associent l'observation exceptionnelle de la faune à des lodges cinq étoiles, des concessions privées et des itinéraires sur mesure. Imaginez des sundowners au bord du cratère, des dîners en brousse aux chandelles sous les étoiles et un accès exclusif aux zones les plus reculées.\n\nSéjournez dans des établissements primés — du Ngorongoro Crater Lodge au Four Seasons Safari Lodge Serengeti. Chaque détail est soigné : vins premium, majordome personnel, guide privé et vols charters entre les destinations.\n\nQu'il s'agisse d'une célébration, d'un voyage unique ou simplement de votre style de voyage, nos safaris de luxe transforment chaque safari en une expérience cinq étoiles inoubliable.",
            'de' => "Gönnen Sie sich das beste Safari-Erlebnis, das Afrika zu bieten hat. Unsere Luxus-Safaris verbinden erstklassige Wildtierbeobachtung mit Fünf-Sterne-Lodges, privaten Konzessionen und maßgeschneiderten Reiserouten. Denken Sie an Sundowner am Kraterrand, Candlelight-Dinner im Busch unter Sternen und exklusiven Zugang zu abgelegenen Gebieten.\n\nÜbernachten Sie in preisgekrönten Unterkünften — von der Ngorongoro Crater Lodge bis zur Four Seasons Safari Lodge Serengeti. Jedes Detail ist kuratiert: Premiumweine, persönliche Butler, private Guides und nahtlose Charterflüge.\n\nOb Meilenstein-Feier, einmalige Reise oder einfach Ihr bevorzugter Reisestil — unsere Luxus-Safaris verwandeln jeden Gamedrives in ein unvergessliches Fünf-Sterne-Erlebnis.",
            'es' => "Disfruta de la mejor experiencia safari que África puede ofrecer. Nuestros safaris de lujo combinan la observación de fauna de primer nivel con alojamientos de cinco estrellas, concesiones privadas e itinerarios a medida. Imagina sundowners al borde del cráter, cenas con velas en la sabana bajo las estrellas y acceso exclusivo a zonas remotas.\n\nAlójate en propiedades galardonadas — desde el Ngorongoro Crater Lodge hasta el Four Seasons Safari Lodge Serengeti. Cada detalle está cuidado: vinos premium, mayordomos personales, guías privados y vuelos chárter entre destinos.\n\nYa sea una celebración especial, un viaje único o tu estilo de viaje preferido, nuestros safaris de lujo transforman cada recorrido en una experiencia cinco estrellas inolvidable.",
        ],
    ],

    // ──────────────────────────────────────────────
    // 4. Honeymoon Safari
    // ──────────────────────────────────────────────
    'honeymoon-safari' => [
        'description' => "Celebrate your love story with a romantic safari honeymoon through Tanzania's most breathtaking landscapes. Our honeymoon safaris blend thrilling bush encounters with intimate beach escapes — from sunrise game drives in the Serengeti to candlelit dinners on the white sands of Zanzibar.\n\nWe hand-pick lodges and camps known for romance: private plunge pools overlooking the bush, couples' spa treatments, champagne sundowners on the savanna, and exclusive honeymoon suites with panoramic vistas. Every transfer, every meal, and every moment is designed for two.\n\nThe classic combination is a four-night Serengeti-Ngorongoro bush safari followed by three or four nights on Zanzibar's turquoise shores. But we can also curate alternatives — a Selous riverside escape, a Ruaha wilderness retreat, or a hot-air balloon ride over the migration. Your honeymoon, your way.",

        'meta_title'       => 'Honeymoon Safari Tanzania | Romantic Bush & Beach | Lomo Safari',
        'meta_description' => 'Plan a romantic honeymoon safari in Tanzania. Combine Serengeti game drives with Zanzibar beach relaxation. Private suites, couples\' spa & sunset champagne.',
        'meta_keywords'    => 'honeymoon safari tanzania, romantic safari, bush and beach honeymoon, zanzibar honeymoon, serengeti romantic getaway, african honeymoon package',

        'description_translations' => [
            'fr' => "Célébrez votre histoire d'amour avec un safari lune de miel romantique à travers les paysages les plus époustouflants de Tanzanie. Nos safaris lune de miel allient des rencontres palpitantes en brousse à des escapades balnéaires intimes — des safaris au lever du soleil dans le Serengeti aux dîners aux chandelles sur les sables blancs de Zanzibar.\n\nNous sélectionnons des lodges réputés pour la romance : piscines privées avec vue sur la brousse, soins spa en couple, sundowners au champagne et suites lune de miel avec vues panoramiques. Chaque transfert, chaque repas est pensé pour deux.\n\nLa combinaison classique comprend quatre nuits de safari dans le Serengeti-Ngorongoro suivies de trois ou quatre nuits sur les rivages turquoise de Zanzibar. Votre lune de miel, à votre façon.",
            'de' => "Feiern Sie Ihre Liebesgeschichte mit einer romantischen Safari-Hochzeitsreise durch Tansanias atemberaubendste Landschaften. Unsere Flitterwochen-Safaris verbinden aufregende Bush-Erlebnisse mit intimen Strandeskapaden — von Pirschfahrten bei Sonnenaufgang in der Serengeti bis zu Candlelight-Dinner am weißen Strand von Sansibar.\n\nWir wählen Lodges, die für Romantik bekannt sind: private Tauchbecken mit Blick auf den Busch, Paar-Spa-Behandlungen, Champagner-Sundowner und Honeymoon-Suiten mit Panoramablick. Jeder Transfer, jede Mahlzeit ist für zwei gestaltet.\n\nDie klassische Kombination umfasst vier Nächte Safari in der Serengeti-Ngorongoro, gefolgt von drei oder vier Nächten an Sansibars türkisfarbener Küste. Ihre Hochzeitsreise, Ihr Weg.",
            'es' => "Celebra tu historia de amor con una luna de miel safari por los paisajes más impresionantes de Tanzania. Nuestros safaris de luna de miel combinan emocionantes encuentros en la sabana con escapadas íntimas a la playa — desde safaris al amanecer en el Serengeti hasta cenas con velas en las arenas blancas de Zanzíbar.\n\nSeleccionamos alojamientos conocidos por el romanticismo: piscinas privadas con vistas a la sabana, tratamientos de spa para parejas, sundowners con champán y suites de luna de miel con vistas panorámicas.\n\nLa combinación clásica incluye cuatro noches de safari en el Serengeti-Ngorongoro seguidas de tres o cuatro noches en las costas turquesas de Zanzíbar. Tu luna de miel, a tu manera.",
        ],
    ],

    // ──────────────────────────────────────────────
    // 5. Cultural Immersion
    // ──────────────────────────────────────────────
    'cultural-immersion' => [
        'description' => "Go beyond the game drive and connect with the people and traditions that make East Africa truly extraordinary. Our cultural immersion safaris offer authentic, respectful encounters with Maasai warriors, Hadzabe hunter-gatherers, Datoga blacksmiths, and Swahili communities — experiences that add depth and meaning to every journey.\n\nVisit a Maasai boma to learn about cattle herding, beadwork, and warrior rites of passage. Join a Hadzabe hunting expedition at dawn and experience one of the last hunter-gatherer lifestyles on Earth. Explore Stone Town's winding alleys, spice plantations, and centuries-old Swahili architecture on the coast.\n\nCultural safaris are seamlessly woven into wildlife itineraries — a morning with the Maasai before an afternoon game drive, or a community visit between national parks. Every interaction is community-led and contributes directly to local livelihoods, education, and cultural preservation.",

        'meta_title'       => 'Cultural Safari Tanzania | Maasai & Hadzabe Encounters | Lomo Safari',
        'meta_description' => 'Experience authentic cultural safaris in Tanzania. Visit Maasai villages, join Hadzabe hunts & explore Stone Town. Community-led encounters woven into wildlife itineraries.',
        'meta_keywords'    => 'cultural safari tanzania, maasai village visit, hadzabe tribe, tanzania cultural tour, stone town tour, african cultural experience',

        'description_translations' => [
            'fr' => "Allez au-delà du safari et connectez-vous avec les peuples et traditions qui rendent l'Afrique de l'Est véritablement extraordinaire. Nos safaris d'immersion culturelle proposent des rencontres authentiques et respectueuses avec les guerriers Maasaï, les chasseurs-cueilleurs Hadzabe, les forgerons Datoga et les communautés swahilies.\n\nVisitez un boma maasaï pour découvrir l'élevage, le travail de perles et les rites de passage des guerriers. Participez à une expédition de chasse Hadzabe à l'aube. Explorez les ruelles de Stone Town, ses plantations d'épices et son architecture swahilie centenaire.\n\nLes safaris culturels s'intègrent parfaitement aux itinéraires animaliers — une matinée avec les Maasaï avant un safari l'après-midi. Chaque interaction est dirigée par la communauté et contribue directement aux moyens de subsistance locaux.",
            'de' => "Gehen Sie über die Pirschfahrt hinaus und verbinden Sie sich mit den Menschen und Traditionen, die Ostafrika wirklich außergewöhnlich machen. Unsere kulturellen Immersions-Safaris bieten authentische, respektvolle Begegnungen mit Maasai-Kriegern, Hadzabe-Jägern und Sammlern, Datoga-Schmieden und Swahili-Gemeinschaften.\n\nBesuchen Sie ein Maasai-Boma, um mehr über Viehzucht, Perlenarbeit und Krieger-Initiationsriten zu erfahren. Nehmen Sie an einer Hadzabe-Jagdexpedition bei Sonnenaufgang teil. Erkunden Sie die Gassen von Stone Town, Gewürzplantagen und jahrhundertealte Swahili-Architektur.\n\nKulturelle Safaris werden nahtlos in Wildlife-Reiserouten eingewoben — ein Morgen mit den Maasai vor einer Nachmittags-Pirschfahrt. Jede Interaktion wird von der Gemeinschaft geleitet und trägt direkt zum lokalen Lebensunterhalt bei.",
            'es' => "Ve más allá del safari y conéctate con las personas y tradiciones que hacen de África Oriental un lugar verdaderamente extraordinario. Nuestros safaris de inmersión cultural ofrecen encuentros auténticos y respetuosos con guerreros Maasai, cazadores-recolectores Hadzabe, herreros Datoga y comunidades suajili.\n\nVisita un boma maasai para aprender sobre el pastoreo, el trabajo con cuentas y los ritos de iniciación guerrera. Únete a una expedición de caza Hadzabe al amanecer. Explora los callejones de Stone Town, las plantaciones de especias y la arquitectura suajili centenaria.\n\nLos safaris culturales se integran perfectamente en los itinerarios de fauna — una mañana con los Maasai antes de un safari por la tarde. Cada interacción es liderada por la comunidad y contribuye directamente al sustento local.",
        ],
    ],

    // ──────────────────────────────────────────────
    // 6. Beach & Island
    // ──────────────────────────────────────────────
    'beach-island' => [
        'description' => "Complete your East African adventure with a tropical beach escape on the stunning shores of Zanzibar, Pemba Island, and the Tanzanian coast. Our beach and island holidays pair perfectly with any safari — offering the ultimate bush-to-beach combination that Tanzania is famous for.\n\nZanzibar enchants with turquoise waters, powdery white sand, world-class snorkelling and diving on coral reefs, and the UNESCO-listed Stone Town with its spice markets and rooftop restaurants. Pemba Island — Zanzibar's quieter neighbour — offers pristine dive sites, mangrove kayaking, and secluded luxury resorts for total privacy.\n\nChoose from barefoot-luxury beach villas, overwater bungalows, and boutique Swahili retreats. Activities range from dolphin-watching boat trips and sunset dhow cruises to kite-surfing, deep-sea fishing, and spice-farm tours. Whether you need three days of post-safari relaxation or a full week of island exploration, we tailor every beach extension to your rhythm.",

        'meta_title'       => 'Beach & Island Holidays Tanzania | Zanzibar & Pemba | Lomo Safari',
        'meta_description' => 'Extend your safari with a Zanzibar or Pemba Island beach holiday. Snorkelling, diving, dhow cruises & luxury beachfront resorts. Bush-to-beach packages available.',
        'meta_keywords'    => 'zanzibar beach holiday, pemba island, tanzania beach vacation, snorkelling zanzibar, bush and beach safari, zanzibar diving, indian ocean islands',

        'description_translations' => [
            'fr' => "Complétez votre aventure est-africaine par une escapade balnéaire tropicale sur les rivages de Zanzibar, de l'île de Pemba et de la côte tanzanienne. Nos vacances plage et île s'associent parfaitement à tout safari — offrant la combinaison brousse-plage dont la Tanzanie est célèbre.\n\nZanzibar enchante avec ses eaux turquoise, son sable blanc, ses spots de snorkelling et plongée de classe mondiale sur les récifs coralliens, et la ville de Stone Town classée UNESCO. L'île de Pemba — la voisine plus tranquille — offre des sites de plongée vierges, du kayak dans les mangroves et des resorts isolés.\n\nChoisissez parmi des villas pieds dans l'eau, des bungalows sur pilotis et des retraites boutique swahilies. Les activités vont des sorties d'observation des dauphins aux croisières en dhow au coucher du soleil, en passant par le kite-surf et les visites de plantations d'épices.",
            'de' => "Vervollständigen Sie Ihr ostafrikanisches Abenteuer mit einem tropischen Strandurlaub an den atemberaubenden Küsten von Sansibar, Pemba Island und der tansanischen Küste. Unsere Strand- und Inselurlaube ergänzen jede Safari perfekt — und bieten die ultimative Bush-to-Beach-Kombination.\n\nSansibar verzaubert mit türkisfarbenem Wasser, pudrig weißem Sand, erstklassigem Schnorcheln und Tauchen an Korallenriffen und der UNESCO-gelisteten Stone Town. Pemba Island — Sansibars ruhigerer Nachbar — bietet unberührte Tauchplätze, Mangroven-Kajakfahren und abgeschiedene Luxusresorts.\n\nWählen Sie aus Barefoot-Luxury-Strandvillen, Überwasser-Bungalows und Boutique-Swahili-Retreats. Aktivitäten reichen von Delfinbeobachtungstouren und Dhow-Sonnenuntergangskreuzfahrten bis zu Kitesurfen und Gewürzfarm-Touren.",
            'es' => "Completa tu aventura en África Oriental con una escapada tropical en las impresionantes costas de Zanzíbar, la isla de Pemba y la costa tanzana. Nuestras vacaciones de playa e isla se combinan perfectamente con cualquier safari — ofreciendo la combinación definitiva de sabana y playa.\n\nZanzíbar encanta con sus aguas turquesas, arena blanca como polvo, snorkel y buceo de primera clase en arrecifes de coral, y la ciudad de Stone Town declarada Patrimonio de la UNESCO. La isla de Pemba — la vecina más tranquila — ofrece sitios de buceo prístinos, kayak en manglares y resorts de lujo aislados.\n\nElige entre villas de lujo descalzo frente al mar, bungalós sobre el agua y retiros boutique suajili. Las actividades van desde avistamiento de delfines y cruceros en dhow al atardecer hasta kitesurf y visitas a plantaciones de especias.",
        ],
    ],

    // ──────────────────────────────────────────────
    // 7. Mountain Trekking
    // ──────────────────────────────────────────────
    'mountain-trekking' => [
        'description' => "Conquer Africa's highest peaks with our expertly guided mountain trekking expeditions. Mount Kilimanjaro — the Roof of Africa at 5,895 metres — is the centrepiece, but our trekking portfolio also includes Mount Meru, the Crater Highlands, and the Usambara Mountains for every fitness level and ambition.\n\nKilimanjaro offers seven established routes, each with a distinct character: the scenic Lemosho, the challenging Umbwe, the classic Machame, the comfortable Marangu with its mountain huts, the remote Northern Circuit, and the Rongai approach from Kenya. We maintain the highest safety standards with certified mountain guides, emergency oxygen, pulse oximeters, and portable Gamow bags on every climb.\n\nBeyond Kilimanjaro, Mount Meru (4,566 m) provides a superb acclimatisation trek with stunning views and fewer crowds. Our highland treks in the Ngorongoro Highlands and Ol Doinyo Lengai — Tanzania's only active volcano — combine trekking with cultural encounters and wildlife sightings.",

        'meta_title'       => 'Mountain Trekking Tanzania | Kilimanjaro & Mount Meru | Lomo Safari',
        'meta_description' => 'Trek Kilimanjaro, Mount Meru & Tanzania\'s highlands. 7 Kilimanjaro routes, certified guides, safety equipment & acclimatisation programs. Book your summit adventure.',
        'meta_keywords'    => 'kilimanjaro trekking, mount meru trek, tanzania mountain climbing, machame route, lemosho route, kilimanjaro summit, african mountain trek',

        'description_translations' => [
            'fr' => "Conquérez les plus hauts sommets d'Afrique avec nos expéditions de trekking en montagne guidées par des experts. Le Kilimandjaro — le Toit de l'Afrique à 5 895 mètres — est la pièce maîtresse, mais notre offre comprend aussi le Mont Meru, les Crater Highlands et les Monts Usambara pour tous les niveaux.\n\nLe Kilimandjaro propose sept voies établies, chacune avec un caractère distinct : la panoramique Lemosho, la stimulante Umbwe, la classique Machame, la confortable Marangu avec ses refuges, la reculée Northern Circuit et l'approche Rongai depuis le Kenya. Nous maintenons les plus hauts standards de sécurité.\n\nAu-delà du Kilimandjaro, le Mont Meru (4 566 m) offre un excellent trek d'acclimatation avec des vues superbes et moins de monde. Nos treks dans les Ngorongoro Highlands et l'Ol Doinyo Lengai — le seul volcan actif de Tanzanie — combinent trekking, culture et observations de faune.",
            'de' => "Bezwingen Sie Afrikas höchste Gipfel mit unseren fachkundig geführten Bergwander-Expeditionen. Der Kilimandscharo — das Dach Afrikas mit 5.895 Metern — steht im Mittelpunkt, aber unser Trekking-Portfolio umfasst auch den Mount Meru, die Crater Highlands und die Usambara-Berge für jedes Fitnesslevel.\n\nDer Kilimandscharo bietet sieben etablierte Routen, jede mit eigenem Charakter: die panoramareiche Lemosho, die herausfordernde Umbwe, die klassische Machame, die komfortable Marangu mit Berghütten, den abgelegenen Northern Circuit und die Rongai-Route von Kenia. Wir halten höchste Sicherheitsstandards ein.\n\nÜber den Kilimandscharo hinaus bietet der Mount Meru (4.566 m) einen hervorragenden Akklimatisierungstrek mit atemberaubenden Aussichten. Unsere Highlands-Treks im Ngorongoro-Hochland und Ol Doinyo Lengai — Tansanias einziger aktiver Vulkan — verbinden Trekking mit kulturellen Begegnungen.",
            'es' => "Conquista los picos más altos de África con nuestras expediciones de trekking de montaña guiadas por expertos. El Kilimanjaro — el Techo de África a 5.895 metros — es la pieza central, pero nuestro portafolio también incluye el Monte Meru, las Tierras Altas del Cráter y las Montañas Usambara para todos los niveles.\n\nEl Kilimanjaro ofrece siete rutas establecidas, cada una con carácter propio: la panorámica Lemosho, la desafiante Umbwe, la clásica Machame, la cómoda Marangu con refugios, el remoto Northern Circuit y la aproximación Rongai desde Kenia. Mantenemos los más altos estándares de seguridad.\n\nMás allá del Kilimanjaro, el Monte Meru (4.566 m) ofrece un excelente trekking de aclimatación con vistas impresionantes. Nuestros treks en las Tierras Altas del Ngorongoro y el Ol Doinyo Lengai — el único volcán activo de Tanzania — combinan trekking con encuentros culturales.",
        ],
    ],

    // ──────────────────────────────────────────────
    // 8. Family Safari
    // ──────────────────────────────────────────────
    'family-safari' => [
        'description' => "Create lifelong memories with a family safari designed for adventurers of all ages. Tanzania offers some of the best family-friendly safari experiences in Africa — from child-safe lodges with swimming pools and junior ranger programmes to shorter game drives, nature walks, and hands-on bush activities that keep young explorers engaged.\n\nOur family itineraries focus on variety and pacing. Mornings feature exciting game drives to spot the Big Five, while afternoons include cultural visits, bush craft lessons, guided nature walks, and wildlife quizzes with our specialist family guides. We select lodges with interconnecting family rooms, dedicated kids' menus, babysitting services, and malaria-free options where available.\n\nPopular family routes include the Ngorongoro Crater and Tarangire — both offering excellent wildlife with shorter driving distances — followed by optional beach time on Zanzibar. We welcome families with children of all ages, including toddlers, and adapt every aspect of the safari to your family's needs and interests.",

        'meta_title'       => 'Family Safari Tanzania | Kid-Friendly Game Drives | Lomo Safari',
        'meta_description' => 'Plan a family safari in Tanzania. Child-friendly lodges, junior ranger programs, shorter game drives & Zanzibar beach extensions. Safe adventures for all ages.',
        'meta_keywords'    => 'family safari tanzania, kid friendly safari, family lodge africa, tanzania with kids, junior ranger safari, family game drive, ngorongoro family trip',

        'description_translations' => [
            'fr' => "Créez des souvenirs inoubliables avec un safari familial conçu pour les aventuriers de tous âges. La Tanzanie offre certaines des meilleures expériences safari familiales d'Afrique — des lodges sécurisés pour enfants avec piscines et programmes junior ranger aux safaris plus courts et activités de brousse éducatives.\n\nNos itinéraires familiaux privilégient variété et rythme. Les matinées proposent des safaris pour observer les Big Five, tandis que les après-midis incluent des visites culturelles, des leçons de survie en brousse et des quiz animaliers. Nous sélectionnons des lodges avec chambres familiales communicantes, menus enfants et services de garde.\n\nLes parcours familiaux populaires incluent le cratère du Ngorongoro et Tarangire — offrant une faune excellente avec des distances de conduite réduites — suivis d'un temps plage optionnel à Zanzibar. Nous accueillons les familles avec enfants de tous âges.",
            'de' => "Schaffen Sie lebenslange Erinnerungen mit einer Familien-Safari für Abenteurer jeden Alters. Tansania bietet einige der besten familienfreundlichen Safari-Erlebnisse Afrikas — von kindersicheren Lodges mit Schwimmbädern und Junior-Ranger-Programmen bis zu kürzeren Pirschfahrten und Buschaktivitäten.\n\nUnsere Familienreiserouten konzentrieren sich auf Abwechslung und Tempo. Vormittags gibt es aufregende Pirschfahrten für die Big Five, nachmittags kulturelle Besuche, Buschhandwerk-Lektionen und Wildlife-Quiz mit unseren Familienguides. Wir wählen Lodges mit verbundenen Familienzimmern, Kindermenüs und Babysitter-Service.\n\nBeliebte Familienrouten umfassen den Ngorongoro-Krater und Tarangire — mit ausgezeichneter Tierwelt bei kürzeren Fahrtstrecken — gefolgt von optionaler Strandzeit auf Sansibar. Wir heißen Familien mit Kindern jeden Alters willkommen.",
            'es' => "Crea recuerdos inolvidables con un safari familiar diseñado para aventureros de todas las edades. Tanzania ofrece algunas de las mejores experiencias de safari familiar en África — desde alojamientos seguros para niños con piscinas y programas de ranger junior hasta safaris más cortos y actividades educativas en la sabana.\n\nNuestros itinerarios familiares se centran en variedad y ritmo. Las mañanas ofrecen emocionantes safaris para avistar los Cinco Grandes, mientras que las tardes incluyen visitas culturales, lecciones de supervivencia y quiz de fauna con nuestros guías familiares. Seleccionamos alojamientos con habitaciones familiares conectadas, menús infantiles y servicio de niñera.\n\nLas rutas familiares populares incluyen el cráter del Ngorongoro y Tarangire — con excelente fauna y distancias de conducción más cortas — seguidas de tiempo opcional en la playa de Zanzíbar. Damos la bienvenida a familias con niños de todas las edades.",
        ],
    ],

    // ──────────────────────────────────────────────
    // 9. Photography Safari
    // ──────────────────────────────────────────────
    'photography-safari' => [
        'description' => "Capture Africa's most iconic wildlife moments with a photography safari designed for shutterbugs, from beginners to professional photographers. Our photo-specific safaris feature modified 4×4 vehicles with pop-up roofs, window mounts, bean-bag supports, and charging stations — giving you the perfect platform for that award-winning shot.\n\nOur specialist photography guides understand animal behaviour, light, and composition. They position vehicles for golden-hour frontlighting at dawn, backlit silhouettes at dusk, and dramatic low-angle perspectives at eye level with predators. We spend longer at sightings, avoid crowded viewing spots, and time our routes for optimal photographic conditions.\n\nIdeal photography safari locations include the Serengeti's Seronera Valley for big cats, Lake Manyara for flamingos and tree-climbing lions, Tarangire for elephant herds against baobab backdrops, and the Ngorongoro Crater for wide-angle wildlife panoramas. Post-safari, optional editing workshops help you process your images in the field.",

        'meta_title'       => 'Photography Safari Tanzania | Wildlife Photo Tours | Lomo Safari',
        'meta_description' => 'Join a photography safari in Tanzania. Modified vehicles, expert photo guides, golden-hour positioning & editing workshops. Capture the Big Five in the Serengeti.',
        'meta_keywords'    => 'photography safari tanzania, wildlife photo tour, serengeti photography, africa photo safari, big cat photography, safari camera vehicle, wildlife photography workshop',

        'description_translations' => [
            'fr' => "Capturez les moments les plus emblématiques de la faune africaine avec un safari photographique conçu pour les passionnés, des débutants aux professionnels. Nos safaris photo disposent de véhicules 4×4 modifiés avec toits relevables, supports de fenêtre, bean-bags et stations de charge.\n\nNos guides photographes spécialisés comprennent le comportement animal, la lumière et la composition. Ils positionnent les véhicules pour la lumière dorée à l'aube, les silhouettes à contre-jour au crépuscule et les perspectives dramatiques à hauteur des prédateurs. Nous restons plus longtemps sur les observations et évitons les points bondés.\n\nLes lieux idéaux incluent la vallée de Seronera au Serengeti pour les grands félins, le lac Manyara pour les flamants, Tarangire pour les troupeaux d'éléphants devant les baobabs, et le cratère du Ngorongoro pour les panoramas grand-angle.",
            'de' => "Fangen Sie Afrikas ikonischste Wildtiermomente mit einer Foto-Safari ein, die für Fotobegeisterte konzipiert ist — vom Anfänger bis zum Profi. Unsere Foto-Safaris verfügen über modifizierte 4×4-Fahrzeuge mit Aufstelldächern, Fensterstützen, Bean-Bag-Auflagen und Ladestationen.\n\nUnsere spezialisierten Fotografieführer verstehen Tierverhalten, Licht und Komposition. Sie positionieren die Fahrzeuge für goldenes Morgenlicht, Silhouetten bei Sonnenuntergang und dramatische Perspektiven auf Augenhöhe mit Raubtieren. Wir verbringen mehr Zeit an Sichtungen und meiden überfüllte Aussichtspunkte.\n\nIdeale Standorte umfassen das Seronera-Tal der Serengeti für Großkatzen, den Manyara-See für Flamingos, Tarangire für Elefantenherden vor Baobab-Kulissen und den Ngorongoro-Krater für Weitwinkel-Wildtierpanoramen.",
            'es' => "Captura los momentos más icónicos de la fauna africana con un safari fotográfico diseñado para aficionados y profesionales. Nuestros safaris foto cuentan con vehículos 4×4 modificados con techos elevables, soportes de ventana, bean-bags y estaciones de carga.\n\nNuestros guías fotográficos especializados entienden el comportamiento animal, la luz y la composición. Posicionan los vehículos para la luz dorada del amanecer, siluetas a contraluz al anochecer y perspectivas dramáticas a nivel de los depredadores. Pasamos más tiempo en los avistamientos y evitamos puntos concurridos.\n\nLas ubicaciones ideales incluyen el valle Seronera del Serengeti para grandes felinos, el lago Manyara para flamencos, Tarangire para manadas de elefantes con baobabs de fondo, y el cráter del Ngorongoro para panoramas de fauna con gran angular.",
        ],
    ],

    // ──────────────────────────────────────────────
    // 10. Walking Safari
    // ──────────────────────────────────────────────
    'walking-safari' => [
        'description' => "Step out of the vehicle and into the wild on a walking safari — the most intimate and exhilarating way to experience the African bush. Led by armed rangers and certified walking guides, you will track animals on foot, read spoor in the dust, identify medicinal plants, and feel the pulse of the savanna in a way no game drive can match.\n\nWalking safaris in Tanzania are offered in select wilderness areas — the Selous (Nyerere National Park), Ruaha, Tarangire, and the western Serengeti — where the terrain and wildlife density create safe, rewarding walking conditions. Routes range from gentle two-hour morning walks to multi-day fly-camping expeditions where you sleep under the stars.\n\nThis is safari at its most raw and authentic. Without the engine noise, your senses sharpen — you hear the alarm call of a francolin, catch the scent of wild sage, and spot dung beetles at work. Walking safaris pair beautifully with conventional game drives, offering a multi-sensory experience that transforms your understanding of the African landscape.",

        'meta_title'       => 'Walking Safari Tanzania | Guided Bush Walks | Lomo Safari',
        'meta_description' => 'Experience walking safaris in Tanzania. Track wildlife on foot with armed rangers in the Selous, Ruaha & Serengeti. Multi-day fly-camping & morning bush walks.',
        'meta_keywords'    => 'walking safari tanzania, bush walk safari, guided walking safari, selous walking safari, ruaha bush walk, fly camping tanzania, african walking safari',

        'description_translations' => [
            'fr' => "Sortez du véhicule et plongez dans la nature lors d'un safari à pied — la manière la plus intime et exaltante de découvrir la brousse africaine. Guidé par des rangers armés et des guides de marche certifiés, vous suivrez les animaux à pied, lirez les traces dans la poussière et identifierez les plantes médicinales.\n\nLes safaris à pied en Tanzanie sont proposés dans des zones de brousse sélectionnées — le Selous (parc national de Nyerere), Ruaha, Tarangire et l'ouest du Serengeti. Les parcours vont de douces marches matinales de deux heures à des expéditions de plusieurs jours en fly-camping sous les étoiles.\n\nC'est le safari dans sa forme la plus brute et authentique. Sans le bruit du moteur, vos sens s'aiguisent — vous entendez le cri d'alerte du francolin, captez le parfum de la sauge sauvage. Les safaris à pied se combinent parfaitement avec les safaris en véhicule pour une expérience multi-sensorielle.",
            'de' => "Steigen Sie aus dem Fahrzeug und erleben Sie die Wildnis auf einer Walking Safari — die intimste und aufregendste Art, den afrikanischen Busch zu erfahren. Geführt von bewaffneten Rangern und zertifizierten Wanderführern verfolgen Sie Tiere zu Fuß, lesen Spuren im Staub und identifizieren Heilpflanzen.\n\nWalking Safaris in Tansania werden in ausgewählten Wildnisgebieten angeboten — dem Selous (Nyerere-Nationalpark), Ruaha, Tarangire und der westlichen Serengeti. Routen reichen von sanften zweistündigen Morgenwanderungen bis zu mehrtägigen Fly-Camping-Expeditionen unter den Sternen.\n\nDies ist Safari in seiner ursprünglichsten Form. Ohne Motorenlärm schärfen sich Ihre Sinne — Sie hören den Alarmruf eines Frankolin, fangen den Duft von wildem Salbei ein. Walking Safaris ergänzen konventionelle Pirschfahrten perfekt für ein multi-sensorisches Erlebnis.",
            'es' => "Sal del vehículo y adéntrate en la naturaleza en un safari a pie — la manera más íntima y emocionante de experimentar la sabana africana. Guiado por rangers armados y guías de caminata certificados, rastrearás animales a pie, leerás huellas en el polvo e identificarás plantas medicinales.\n\nLos safaris a pie en Tanzania se ofrecen en áreas silvestres selectas — el Selous (Parque Nacional Nyerere), Ruaha, Tarangire y el oeste del Serengeti. Las rutas van desde suaves caminatas matinales de dos horas hasta expediciones de varios días acampando bajo las estrellas.\n\nEste es el safari en su forma más pura y auténtica. Sin el ruido del motor, tus sentidos se agudizan — escuchas la llamada de alarma del francolín, captas el aroma de la salvia silvestre. Los safaris a pie se combinan perfectamente con los safaris en vehículo para una experiencia multisensorial.",
        ],
    ],

    // ──────────────────────────────────────────────
    // 11. Bird Watching
    // ──────────────────────────────────────────────
    'bird-watching' => [
        'description' => "Tanzania is one of the world's premier birding destinations, home to over 1,100 recorded species — from vast flamingo flocks painting Lake Manyara pink to the elusive Usambara eagle-owl and the spectacular lilac-breasted roller. Our bird watching safaris are led by specialist ornithologist guides who know every call, nest site, and seasonal migration pattern.\n\nKey birding hotspots include Lake Manyara and Lake Natron for flamingos and waterbirds, the Serengeti for raptors and secretary birds, Tarangire for endemic species like the ashy starling and yellow-collared lovebird, the Usambara Mountains for Albertine Rift endemics, and the coastal forests of the Eastern Arc for globally threatened species.\n\nBirding safaris can be standalone trips for dedicated twitchers — complete with checklists, spotting scopes, and field guides — or seamlessly integrated into wildlife safaris as an enrichment layer. Early mornings and late afternoons offer the best sightings. We also arrange specialist trips during peak migration seasons (November–April) when Palearctic migrants swell Tanzania's bird count dramatically.",

        'meta_title'       => 'Bird Watching Safari Tanzania | 1,100+ Species | Lomo Safari',
        'meta_description' => 'Discover 1,100+ bird species on a birding safari in Tanzania. Expert ornithologist guides, Lake Manyara flamingos, Usambara endemics & Serengeti raptors.',
        'meta_keywords'    => 'bird watching tanzania, birding safari, lake manyara flamingos, tanzania bird species, usambara birds, african birding tour, ornithology safari',

        'description_translations' => [
            'fr' => "La Tanzanie est l'une des premières destinations d'observation d'oiseaux au monde, abritant plus de 1 100 espèces — des immenses colonies de flamants qui teintent le lac Manyara en rose au discret hibou grand-duc des Usambara et au spectaculaire rollier à longs brins. Nos safaris ornithologiques sont menés par des guides spécialistes qui connaissent chaque chant et site de nidification.\n\nLes points chauds incluent le lac Manyara et le lac Natron pour les flamants, le Serengeti pour les rapaces, Tarangire pour les endémiques comme l'étourneau cendré, les monts Usambara pour les endémiques du Rift Albertin, et les forêts côtières de l'Arc Oriental pour les espèces menacées.\n\nLes safaris ornithologiques peuvent être des voyages dédiés pour les passionnés — avec listes, longues-vues et guides de terrain — ou intégrés aux safaris animaliers. Nous organisons aussi des voyages spéciaux pendant les migrations paléarctiques (novembre–avril).",
            'de' => "Tansania ist eines der weltweit besten Vogelbeobachtungsgebiete mit über 1.100 erfassten Arten — von riesigen Flamingoschwärmen am Manyara-See bis zum scheuen Usambara-Uhu und dem spektakulären Gabelracken. Unsere Vogelbeobachtungssafaris werden von spezialisierten Ornithologie-Guides geleitet.\n\nWichtige Hotspots umfassen den Manyara-See und Natron-See für Flamingos und Wasservögel, die Serengeti für Greifvögel, Tarangire für endemische Arten wie den Graustar, die Usambara-Berge für Albertine-Rift-Endemiten und die Küstenwälder des Eastern Arc für bedrohte Arten.\n\nVogelbeobachtungssafaris können eigenständige Reisen für Vogelbegeisterte sein — mit Checklisten, Spektiven und Feldführern — oder nahtlos in Wildlife-Safaris integriert werden. Wir organisieren auch Spezialreisen während der paläarktischen Migration (November–April).",
            'es' => "Tanzania es uno de los principales destinos de observación de aves del mundo, hogar de más de 1.100 especies — desde vastas bandadas de flamencos que pintan de rosa el lago Manyara hasta el esquivo búho real de Usambara y el espectacular carraca lila. Nuestros safaris de observación de aves están liderados por guías ornitólogos especialistas.\n\nLos puntos clave incluyen el lago Manyara y lago Natrón para flamencos y aves acuáticas, el Serengeti para rapaces, Tarangire para especies endémicas como el estornino cenizo, las montañas Usambara para endémicas del Rift Albertino, y los bosques costeros del Arco Oriental para especies amenazadas.\n\nLos safaris ornitológicos pueden ser viajes dedicados para observadores expertos — con listas, telescopios y guías de campo — o integrarse en safaris de fauna. También organizamos viajes especiales durante las migraciones paleárticas (noviembre–abril).",
        ],
    ],

    // ──────────────────────────────────────────────
    // 12. Gorilla Trekking
    // ──────────────────────────────────────────────
    'gorilla-trekking' => [
        'description' => "Come face to face with one of humanity's closest relatives on a gorilla trekking expedition in the misty forests of Uganda and Rwanda. With fewer than 1,100 mountain gorillas remaining in the wild, this is among the most extraordinary and moving wildlife experiences on Earth — and one that directly funds their conservation.\n\nIn Uganda, treks depart from Bwindi Impenetrable Forest National Park, a UNESCO World Heritage Site with four habituated gorilla groups. In Rwanda, Volcanoes National Park — made famous by Dian Fossey — offers a more accessible trekking experience with shorter hiking distances. Both destinations guarantee a magical one-hour encounter sitting quietly among a gorilla family as they feed, play, and interact.\n\nWe handle the entire logistics — from securing limited gorilla permits (book well in advance) to arranging luxury lodges on the forest edge, domestic flights, and optional chimpanzee tracking add-ons. Gorilla trekking pairs superbly with a Tanzania wildlife safari for the ultimate East African itinerary.",

        'meta_title'       => 'Gorilla Trekking Uganda & Rwanda | Mountain Gorillas | Lomo Safari',
        'meta_description' => 'Trek to see mountain gorillas in Uganda\'s Bwindi Forest & Rwanda\'s Volcanoes National Park. Permits, luxury lodges & combo safari packages available.',
        'meta_keywords'    => 'gorilla trekking uganda, mountain gorilla safari, bwindi gorilla trek, volcanoes national park rwanda, gorilla permit, gorilla safari africa, east africa gorilla tour',

        'description_translations' => [
            'fr' => "Venez face à face avec l'un des plus proches parents de l'humanité lors d'une expédition de trekking gorille dans les forêts brumeuses de l'Ouganda et du Rwanda. Avec moins de 1 100 gorilles de montagne dans la nature, c'est l'une des expériences les plus extraordinaires au monde — qui finance directement leur conservation.\n\nEn Ouganda, les treks partent de la forêt impénétrable de Bwindi, site UNESCO avec quatre groupes de gorilles habitués. Au Rwanda, le parc national des Volcans — rendu célèbre par Dian Fossey — offre une expérience plus accessible avec des distances de marche plus courtes. Les deux destinations garantissent une heure magique parmi une famille de gorilles.\n\nNous gérons toute la logistique — de l'obtention des permis limités aux lodges de luxe en lisière de forêt, vols domestiques et options de pistage de chimpanzés. Le trekking gorille se combine superbement avec un safari en Tanzanie.",
            'de' => "Begegnen Sie einem der nächsten Verwandten der Menschheit auf einer Gorilla-Trekking-Expedition in den Nebelwäldern Ugandas und Ruandas. Mit weniger als 1.100 Berggorillas in freier Wildbahn ist dies eines der außergewöhnlichsten Wildtiererlebnisse der Erde — und finanziert direkt deren Schutz.\n\nIn Uganda starten Treks vom Bwindi Impenetrable Forest Nationalpark, einem UNESCO-Welterbe mit vier habituierten Gorillagruppen. In Ruanda bietet der Volcanoes National Park — durch Dian Fossey berühmt — ein zugänglicheres Trekking-Erlebnis mit kürzeren Wanderentfernungen. Beide Ziele garantieren eine magische Stunde inmitten einer Gorillafamilie.\n\nWir kümmern uns um die gesamte Logistik — von der Sicherung begrenzter Gorilla-Permits bis zu Luxuslodges am Waldrand, Inlandsflügen und optionalem Schimpansen-Tracking. Gorilla-Trekking ergänzt einen Tansania-Wildlife-Safari hervorragend.",
            'es' => "Ven cara a cara con uno de los parientes más cercanos de la humanidad en una expedición de trekking de gorilas en los bosques nublados de Uganda y Ruanda. Con menos de 1.100 gorilas de montaña en estado salvaje, esta es una de las experiencias más extraordinarias del mundo — y financia directamente su conservación.\n\nEn Uganda, los treks parten del Bosque Impenetrable de Bwindi, Patrimonio UNESCO con cuatro grupos de gorilas habituados. En Ruanda, el Parque Nacional de los Volcanes — famoso por Dian Fossey — ofrece una experiencia más accesible con distancias de caminata más cortas. Ambos destinos garantizan una hora mágica entre una familia de gorilas.\n\nNos encargamos de toda la logística — desde asegurar los permisos limitados hasta alojamientos de lujo al borde del bosque, vuelos domésticos y opciones de rastreo de chimpancés. El trekking de gorilas se combina perfectamente con un safari en Tanzania.",
        ],
    ],
];

// ──────────────────────────────────────────────
// Execute updates
// ──────────────────────────────────────────────
$updated = 0;
$fixed   = 0;

foreach ($tourTypes as $slug => $data) {
    $tourType = TourType::where('slug', $slug)->first();
    if (!$tourType) {
        echo "⚠ Tour type '{$slug}' not found — skipped.\n";
        continue;
    }

    $tourType->update([
        'description'              => $data['description'],
        'meta_title'               => $data['meta_title'],
        'meta_description'         => $data['meta_description'],
        'meta_keywords'            => $data['meta_keywords'],
        'description_translations' => $data['description_translations'],
    ]);

    echo "✓ Updated: {$tourType->name}\n";
    $updated++;
}

// Also fix any remaining ??? in tour_types table
$fixCount = \Illuminate\Support\Facades\DB::table('tour_types')
    ->where('description', 'like', '%???%')
    ->update(['description' => \Illuminate\Support\Facades\DB::raw("REPLACE(description, '???', '—')")]);
$fixed += $fixCount;

echo "\n══════════════════════════════════\n";
echo "Updated: {$updated} tour types\n";
echo "Fixed ???: {$fixed} rows\n";
echo "══════════════════════════════════\n";
